maintainer        "PipelineDeals, LLC."
maintainer_email  "cookbooks@pipelinedealsco.com"
license           "Apache 2.0"
description       "Tunes Ubuntu for a secure high performance environment (i.e. web server, database, etc)."
version           "0.2.0"
recipe            "ubuntu::default", "Executes all cookbooks."
recipe            "ubuntu::apparmor", "Stops and disables the apparmor service on Ubuntu."
recipe            "ubuntu::security", "Hardens a stock Ubuntu installation."
supports          "ubuntu"
